###########################################
## cmd : command from the controller
##		- 01 start
#			- 02 stop
###########################################
string track_cmd
string color_filter_sel
float64 HSV_ts_H_l1
float64 HSV_ts_H_h1
float64 HSV_ts_H_l2
float64 HSV_ts_H_h2
float64 HSV_ts_S_l1
float64 HSV_ts_S_h1
float64 HSV_ts_V_l1
float64 HSV_ts_V_h1
float64 RGB_ts_R_l1
float64 RGB_ts_R_h1
float64 RGB_ts_G_l1
float64 RGB_ts_G_h1
float64 RGB_ts_B_l1
float64 RGB_ts_B_h1

